SET lock_timeout = '1s';
SET statement_timeout = '5s';

CREATE TABLE IF NOT EXISTS refresh_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    is_active BOOLEAN NOT NULL DEFAULT true,
    auth_user_id BIGINT NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE,
    token_hash TEXT UNIQUE NOT NULL CONSTRAINT refresh_token_token_hash_length CHECK (char_length(token_hash) <= 64),
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ
);

-- squawk-ignore require-concurrent-index-creation
CREATE INDEX IF NOT EXISTS idx_refresh_token_auth_user_id ON refresh_token (auth_user_id);
-- squawk-ignore require-concurrent-index-creation
CREATE INDEX IF NOT EXISTS idx_refresh_token_expires_at ON refresh_token (expires_at);
