SET lock_timeout = '1s';
SET statement_timeout = '5s';

CREATE TABLE IF NOT EXISTS auth_group (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    is_active BOOLEAN NOT NULL DEFAULT true,
    name TEXT UNIQUE NOT NULL CONSTRAINT auth_group_name_length CHECK (char_length(name) <= 255),
    description TEXT NOT NULL DEFAULT ''
);

-- squawk-ignore require-concurrent-index-creation
CREATE INDEX IF NOT EXISTS idx_auth_group_created_at ON auth_group (created_at DESC);
