SET lock_timeout = '1s';
SET statement_timeout = '5s';

CREATE TABLE IF NOT EXISTS auth_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    is_active BOOLEAN NOT NULL DEFAULT true,
    email TEXT UNIQUE NOT NULL CONSTRAINT auth_user_email_length CHECK (char_length(email) <= 255),
    password_hash TEXT NOT NULL DEFAULT '' CONSTRAINT auth_user_password_hash_length CHECK (char_length(password_hash) <= 255),
    full_name TEXT NOT NULL DEFAULT '' CONSTRAINT auth_user_full_name_length CHECK (char_length(full_name) <= 200),
    is_staff BOOLEAN NOT NULL DEFAULT false,
    is_superuser BOOLEAN NOT NULL DEFAULT false,
    email_verified_at TIMESTAMPTZ,
    last_login TIMESTAMPTZ,
    provider TEXT NOT NULL DEFAULT 'local' CONSTRAINT auth_user_provider_length CHECK (char_length(provider) <= 50),
    provider_id TEXT CONSTRAINT auth_user_provider_id_length CHECK (char_length(provider_id) <= 255),
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb
);

-- squawk-ignore require-concurrent-index-creation
CREATE INDEX IF NOT EXISTS idx_auth_user_provider ON auth_user (provider);
-- squawk-ignore require-concurrent-index-creation
CREATE INDEX IF NOT EXISTS idx_auth_user_is_active ON auth_user (is_active);
-- squawk-ignore require-concurrent-index-creation
CREATE INDEX IF NOT EXISTS idx_auth_user_created_at ON auth_user (created_at DESC);
-- squawk-ignore require-concurrent-index-creation
CREATE INDEX IF NOT EXISTS idx_auth_user_metadata ON auth_user USING gin (metadata);
